// AUTO-GENERATED by scripts/fetch-social-content.mjs — do not edit by hand.
// Regenerate with: node scripts/fetch-social-content.mjs
// Last fetch: 2026-05-16T00:51:45.347Z

export interface SocialPost {
  id: number;
  type: 'facebook' | 'twitter';
  sourceUrl: string;
  canonicalUrl: string;
  title: string;
  description: string;
  image: string;
  /** false = post deleted, made private, or no longer reachable (auto-detected by scraper) */
  available: boolean;
}

export const SOCIAL_POSTS: SocialPost[] = [
  {
    "id": 1,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/18GvVs4K8V/",
    "canonicalUrl": "https://www.facebook.com/saad.alasaal.2025/posts/%D9%85%D8%B9%D8%B1%D9%81%D8%AA%D9%8A-%D8%A8%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%85%D9%86%D8%B0-%D8%B9%D8%A7%D9%85-2018-%D8%B9%D9%85%D9%84%D8%A7%D9%82-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85-%D8%A7%D9%84%D9%8A%D9%85%D9%86%D9%8A-%D9%84%D9%8A%D8%B3-%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%B4/2483806965378169/",
    "title": "ابووقاص سعد",
    "description": "معرفتي بالأستاذ جميل محمود عزالدين منذ عام 2018 عملاق الإعلام اليمني ليس معرفة شخصية بل معرفة من الفضاء الرقمي على منصة #الفيسبوك ومن منصة #X تويتر سابقاً وجدته انا وغير من الناشطين والإعلاميين...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/688822577_2483806932044839_4435052656455459486_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=111&ccb=1-7&_nc_sid=b96d88&_nc_ohc=JbseOtf9_xIQ7kNvwEe7_Uw&_nc_oc=AdofQ81E03QKUn7okUKub9CyfLLMkkRXHk268uOMcBHkr1WFzwLxxauIQeYC1huCumI&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=r_RKplcZYCf02SjlhdGxGg&_nc_ss=7f289&oh=00_Af5AdU6zxyt6i2IZxA3e07b2V3PckNiICEfPmWc14fAzMA&oe=6A0DA2BA",
    "available": true
  },
  {
    "id": 2,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/184gm31REJ/",
    "canonicalUrl": "https://www.facebook.com/ALSlahi.Abdullh.YEM/posts/%D9%82%D8%A7%D9%84%D9%88%D8%A7-%D8%B9%D8%AC%D8%B2%D8%AA-%D8%A7%D9%84%D8%B1%D8%AF-%D8%B9%D8%A7%D9%84%D9%84%D9%8A-%D9%8A%D8%B3%D8%A8%D9%88%D9%83%D8%A7%D9%88-%D8%AE%D9%81%D9%80%D8%AA-%D9%85%D9%86-%D8%B1%D8%AF%D9%83-%D8%AA%D8%B2%D9%8A%D8%AF-%D8%A7%D9%84%D8%B4%D8%AA%D8%A7%D9%8A%D9%80%D9%85%D8%B1%D8%AF%D9%8A%D8%AA-%D9%85%D8%A7%D9%87%D9%88-%D8%B9%D8%AC%D8%B2-%D9%81%D9%8A-%D8%A7%D9%84%D8%B1%D8%AF-%D9%8A%D8%A7%D8%A8/2862325527444049/",
    "title": "عبدالله الصلاحي",
    "description": "قالوا عجزت الرد عاللي يسبوك\nاو خفـت من ردك تزيد الشتايـم\n\nرديت ماهو عجز في الرد يابوك\nلكن ذكرت اني بـن الحـاج سالـم\n\nوش قول له لوقال لي كيف وطوك\nمن حصن في راس الجبل للتهايم\n\nونسيت اصل اللي على العز...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/687039779_2862325494110719_3179473297691848628_n.jpg?stp=dst-jpg_tt6&cstp=mx540x960&ctp=s540x960&_nc_cat=103&ccb=1-7&_nc_sid=b96d88&_nc_ohc=mkLP6XE4xj0Q7kNvwGVR5Wu&_nc_oc=AdpMDAbxTkFL9DkDjQi17KrdfQ3QuwbYmf4pBS1XxVlHTX72H8cmDiYtnyuA7cOZuiM&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=G4rifB2rZgWmLplE1k6ayw&_nc_ss=7f289&oh=00_Af5mBXWoGrnNmUIJu44jzG6TBOLp7HC2G1box_-H2trAPw&oe=6A0D82ED",
    "available": true
  },
  {
    "id": 3,
    "type": "twitter",
    "sourceUrl": "https://x.com/g_khamre/status/2050969680458727691",
    "canonicalUrl": "https://x.com/g_khamre/status/2050969680458727691",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @g_khamre على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 4,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1FWdCCXQ8p/",
    "canonicalUrl": "https://www.facebook.com/MoneerAlhaj2030/posts/%D9%87%D9%84-%D9%8A%D8%B3%D8%AA%D9%88%D9%8A-%D8%B5%D9%88%D8%AA-%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9-%D9%88%D9%84%D8%B3%D8%A7%D9%86-%D8%A7%D9%84%D9%88%D8%B7%D9%86-%D8%A7%D9%84%D9%81%D8%B5%D9%8A%D8%AD-%D8%B0%D9%84%D9%83-%D8%A7%D9%84%D8%B3%D9%8A%D9%81-%D8%A7%D9%84%D9%85%D8%B4%D8%B1%D8%B9-%D9%81%D9%8A-%D9%88%D8%AC%D9%87-%D8%A7%D9%84%D8%B9%D8%AA%D9%85%D8%A9-%D9%88%D9%84%D8%B3%D8%A7%D9%86-%D8%A7/4450708078495138/",
    "title": "منير الحاج",
    "description": "هل يستوي صوت الجمهورية ولسان الوطن الفصيح، ذلك السيف المشرع في وجه العتمة، ولسان الوطن إذا نطق أنبت المعنى وأورق الحقيقة، وحامل جرح اليمن كقنديل لا ينطفئ في ريح النكبات، مع من ٲضاع بوصلته، و باع صوته...",
    "image": "",
    "available": true
  },
  {
    "id": 5,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1B2KJQvpE3/",
    "canonicalUrl": "https://www.facebook.com/100007677948905/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%84%D9%8A%D8%B3-%D9%85%D8%B8%D8%B7%D8%B1%D8%A7-%D9%84%D9%84%D8%AA%D8%B9%D8%B1%D9%8A%D9%81-%D8%A8%D9%86%D9%81%D8%B3%D9%87%D9%81%D8%AC%D8%A8%D8%A7%D9%84-%D8%A7%D9%84%D9%8A%D9%85%D9%86-%D9%88%D8%B3%D9%87%D9%88%D9%84%D9%87%D8%A7-%D9%88%D9%87%D8%B6%D8%A7%D8%A8%D9%87%D8%A7-%D9%88%D8%AA%D9%84%D8%A7%D9%84%D9%87%D8%A7-%D9%88/4393753657557189/",
    "title": "وحيد وغريب",
    "description": "جميل محمود عز الدين ليس مظطرا للتعريف بنفسه\nفجبال اليمن وسهولها وهضابها وتلالها وأشجارها وأحجارها و شطانها وبحارها يعرفونه ويعرفون من هو جميل عز الدين\n\nيعرفه جن اليمن  وإنسها أمواتها وأحيائها \nيعرفه...",
    "image": "",
    "available": true
  },
  {
    "id": 6,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18Pvuaraqb/",
    "canonicalUrl": "https://www.facebook.com/share/18Pvuaraqb/",
    "title": "",
    "description": "",
    "image": "",
    "available": false
  },
  {
    "id": 7,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18XFqsHok9/",
    "canonicalUrl": "https://www.facebook.com/bdalrhmnalnmr.611808/posts/%D9%81%D9%8A-%D9%85%D9%8A%D8%AF%D8%A7%D9%86-%D8%A7%D9%84%D9%86%D8%B6%D8%A7%D9%84-%D8%A8%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A9-%D8%AA%D8%A8%D8%B1%D8%B2-%D9%85%D8%B9%D8%A7%D8%AF%D9%86-%D8%A7%D9%84%D8%B1%D8%AC%D8%A7%D9%84-%D9%81%D9%87%D9%86%D8%A7%D9%83-%D9%85%D9%86-%D9%8A%D8%B3%D9%83%D8%A8%D9%8F-%D8%AD%D8%A8%D8%B1%D9%87-%D8%AF%D9%85%D8%A7%D9%8B-%D9%88%D9%88%D9%81%D8%A7%D8%A1%D9%8B-%D9%84%D9%84%D9%88%D8%B7%D9%86-/26943116565376454/",
    "title": "عبد الرحمن النمر",
    "description": "في ميدان  النضال بالكلمة، تبرز معادن الرجال فهناك من يسكبُ حبره دماً ووفاءً للوطن ، وهناك من لا يتقنُ سوى رصِّ بضاعة الشتائم التي لا تُسمن ولا تُغني من وعي.\nإن الهجوم الذي يتعرض له القامة الإعلامية...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/686959739_26943105655377545_7208997561526195808_n.jpg?stp=dst-jpg_tt6&cstp=mx1125x1251&ctp=p600x600&_nc_cat=102&ccb=1-7&_nc_sid=b96d88&_nc_ohc=2BbHi143BngQ7kNvwEU2KR-&_nc_oc=AdptuaYgVJjJG6KFNxRwgpHjBV5lqtDfOcDVGAI-qmLfNDT0nwSBOq0Y2RoqdMjnSkE&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=8ZEj68XEqXKTJex40JH4Lg&_nc_ss=7f289&oh=00_Af7m5L_4lRUxFj0rOghwKgMJT9askOrEVP_sz1g4pYchzQ&oe=6A0D9173",
    "available": true
  },
  {
    "id": 8,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18PER5LFQ1/",
    "canonicalUrl": "https://www.facebook.com/61573945325326/posts/%D9%84%D9%85-%D9%86%D8%AC%D8%AF-%D9%85%D9%86-%D8%A7%D9%84%D8%AD%D8%B1%D9%88%D9%81-%D9%85%D8%A7-%D9%8A%D9%83%D9%81%D9%8A-%D9%88%D9%84%D8%A7-%D9%85%D9%86-%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A7%D8%AA-%D9%85%D8%A7-%D9%8A%D9%88%D9%81%D9%8A-%D9%82%D8%AF%D8%B1%D9%83-%D9%8A%D8%A7-%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0%D9%86%D8%A7-%D8%A7%D9%84%D8%BA%D8%A7%D9%84%D9%8A-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88/122173282916798177/",
    "title": "ابو هجررران العلقمي الصبيحي",
    "description": "لم نجد من الحروف ما يكفي، ولا من الكلمات ما يوفي قدرك يا أستاذنا الغالي جميل محمود عزالدين \nفأنت لست مجرد إعلامي عابر، بل قيمة ثابتة، وهامة وطنية ارتفعت فوق كل محاولات التقليل والتشويه.\nأنت صوتٌ حين...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t15.5256-10/685936191_2173990483387528_5435028270101534370_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=a27664&_nc_ohc=ptj09gZxoFoQ7kNvwFAs9H9&_nc_oc=Adpvj1tgT3k82PnnW1EsM5mLPu06Bv1D5PcB14ebDKfPtyWGiQkin7XaTF8y2r529Zg&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=ysW8zD8mr3Muy1PbCsLvJQ&_nc_ss=7f289&oh=00_Af5S72DWaaYAIo0xqA3i4yngf8BJkgqU1x-769FmS4KZeA&oe=6A0DA462",
    "available": true
  },
  {
    "id": 9,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1EFZUNcdPR/",
    "canonicalUrl": "https://www.facebook.com/61561543972459/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%B5%D9%88%D8%AA-%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9-%D9%88%D9%85%D8%AF%D9%81%D8%B9%D9%87%D8%A7-%D9%88%D8%B3%D9%8A%D9%81%D9%87%D8%A7-%D9%88%D8%AD%D8%A7%D8%B1%D8%B3-%D8%B1%D8%A7%D9%8A%D8%A9-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D9%85%D9%86%D8%B0-%D8%A7%D9%86%D9%82/122198630660384799/",
    "title": "ناجي القرطحي",
    "description": "جميل محمود عزالدين … صوت الجمهورية ومدفعها وسيفها، وحارس راية الإعلام الرسمي\n\nمنذ انقلاب الحوثي على الدولة، لم يكن الإعلامي جميل عزالدين مجرد اسم في شاشة أو صوت في نشرة؛ بل كان موقفًا واضحًا في زمن...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/689324899_122198630504384799_2231402025815532837_n.jpg?stp=cp6_dst-jpg_tt6&cstp=mx1320x546&ctp=s1320x546&_nc_cat=105&ccb=1-7&_nc_sid=b96d88&_nc_ohc=TkXHSfYsBRsQ7kNvwEMUHp7&_nc_oc=AdrX_ZxKLKZrLZIRN1SN1tml1Fd6CzRDpGl76itWofGXg3o2w93dBB4BIFFgUYSt78A&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=Z-95c8S30hXoX3YX2-h-qg&_nc_ss=7f289&oh=00_Af6W1sujZadS3Gpq3HCMpcoIk8iGWYnWnk6YyOQjqCv2pA&oe=6A0D76C2",
    "available": true
  },
  {
    "id": 10,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1B8rie1BAd/",
    "canonicalUrl": "https://www.facebook.com/61577506953803/posts/%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AC%D8%A8%D9%84-%D8%B4%D8%A7%D9%85%D8%AE-%D9%84%D8%A7-%D8%AA%D9%87%D8%B2%D9%87-%D8%B1%D9%8A%D8%A7%D8%AD-%D8%A7%D9%84%D8%AD%D8%A7%D9%82%D8%AF%D9%8A%D9%86-%D8%B5%D9%88%D8%AA%D9%87-%D8%A7%D9%84%D8%B0%D9%8A-%D8%B2%D9%84%D8%B2%D9%84-%D8%B9%D8%B1%D9%88%D8%B4-%D8%A7%D9%84/122110727498916898/",
    "title": "الكاتبة عبير فتحي السقاف",
    "description": "الأستاذ جميل محمود عزالدين \nجبل شامخ لا تهزه رياح الحاقدين. صوته الذي زلزل عروش الكهنوت هو الذي أوجعكم، فذهبتتم تبحثون عن شائعات وتهم معلبة لتغطية فشلكم. سيبقى رمزاً إعلامياً وطنياً رغماً عن أنوف...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/688978503_122110727474916898_1247071949093521507_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=108&ccb=1-7&_nc_sid=b96d88&_nc_ohc=yd50qs8nkHcQ7kNvwFvHnOn&_nc_oc=AdqplO5eUgogWLx_RfxA_mhH4SPTbL6RMqOfwvIQNiUeqarv92OlSLzDz1MYLft3-U4&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=V8ovpqVtAvrSpEW8Uu_Hng&_nc_ss=7f289&oh=00_Af609xkmCw6Dupowr36Pl2iaLLNLTbLMWA5avvSJm9x1tw&oe=6A0D765A",
    "available": true
  },
  {
    "id": 11,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1AznrvByEn/",
    "canonicalUrl": "https://www.facebook.com/m.bdalmjyd.mnsr/posts/%D8%A8%D8%B1%D8%A3%D9%8A%D9%8A-%D9%8A%D8%B9%D8%AF-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%85%D9%86-%D8%A7%D9%84%D8%A3%D8%B5%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D8%A7%D9%84%D9%86%D8%A7%D8%AF%D8%B1%D8%A9-%D8%A7%D9%84%D8%AA%D9%8A-%D8%A7%D8%B3%D8%AA%D8%B7%D8%A7%D8%B9%D8%AA-%D8%A3%D9%86-%D8%AA%D8%AA%D8%AD%D8%B1%D8%B1-/2964366860434503/",
    "title": "م.عبدالمجيد منصر",
    "description": "برأيي، يعد جميل محمود عزالدين من الأصوات الإعلامية النادرة التي استطاعت أن تتحرر من قيود الحزبية والانتماءات الضيقة، ولم يكن يوماً أسيراً للمناطقية أو الطائفية، بل ارتقى بخطابه ليجعل الوطن قضيته...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/689014988_2964366830434506_3862785458311420961_n.jpg?stp=dst-jpg_tt6&cstp=mx528x355&ctp=s528x355&_nc_cat=100&ccb=1-7&_nc_sid=b96d88&_nc_ohc=FGr-7SrTm9YQ7kNvwGW6SuW&_nc_oc=AdqIK02h4vKnsbusXpDX7WLe6ardSeBKb4tkVabWUww9zFyKzTVPkwLLOLYF-jeIP7g&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=0cDd9sn080aWCkMeZVvypg&_nc_ss=7f289&oh=00_Af43a51cymWAi1LJRxDtuUq6YgT6o5W9tgNaSYeuyBYlXA&oe=6A0D9D4E",
    "available": true
  },
  {
    "id": 12,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18oWy6feyX/",
    "canonicalUrl": "https://www.facebook.com/waemalsofitaiz/posts/%D9%81%D9%8A-%D8%B2%D9%85%D9%86-%D8%A7%D9%84%D9%85%D8%AA%D8%BA%D9%8A%D8%B1%D8%A7%D8%AA-%D8%A7%D9%84%D9%83%D8%A8%D8%B1%D9%89-%D9%88%D8%A7%D9%84%D9%85%D9%86%D8%B9%D8%B7%D9%81%D8%A7%D8%AA-%D8%A7%D9%84%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A%D8%A9-%D8%A7%D9%84%D9%82%D8%A7%D8%B3%D9%8A%D8%A9-%D8%AA%D8%A8%D8%B1%D8%B2-%D9%82%D8%A7%D9%85%D8%A7%D8%AA-%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D9%84%D8%A7-%D8%AA%D9%83%D8%AA%D9%81%D9%8A/3483625328451328/",
    "title": "وئام الصوفي",
    "description": "في زمن المتغيرات الكبرى والمنعطفات التاريخية القاسية، تبرز قامات إعلامية لا تكتفي بنقل الخبر، بل تصبح هي بذاتها جزءاً من معركة الوجود والهوية. ومن بين هذه الأسماء الشامخة، يتصدر الإعلامي القدير جميل...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/687039169_3483625298451331_3064583629710072530_n.jpg?stp=dst-jpg_tt6&cstp=mx1338x1050&ctp=p600x600&_nc_cat=107&ccb=1-7&_nc_sid=b96d88&_nc_ohc=jWEPebmRzZEQ7kNvwElYTYe&_nc_oc=AdqJIdti8Mg7yEBBdf0A7622Jeh-QTY2bcF3KE_d3gpZoT37CSXzL0AtEy6jn-5PvF8&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=gGoqDH1GFJq3v0kYBFyFRw&_nc_ss=7f289&oh=00_Af5GWV0vDAvbY86y1W5BjTAOq8RTPWCwKra0P8Cgy6SwOg&oe=6A0D7EE2",
    "available": true
  },
  {
    "id": 13,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/18otrMgbMH/",
    "canonicalUrl": "https://www.facebook.com/abw.shhab.al.wady.891500/posts/%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%A7%D9%84%D9%81%D8%A7%D8%B6%D9%84-%D8%A7%D9%84%D8%A7%D8%B9%D9%84%D8%A7%D9%85%D9%8A-%D8%A7%D9%84%D9%82%D8%AF%D9%8A%D8%B1-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AD%D9%81%D8%B8%D9%87-%D8%A7%D9%84%D9%84%D9%87-%D9%88%D8%B1%D8%B9%D8%A7%D9%87-%D8%B8%D9%87%D8%B1%D8%AA-%D9%87%D8%B0%D9%87-%D8%A7%D9%84%D8%A7%D9%8A%D8%A7/4417171195232132/",
    "title": "ابو شهاب العواضي",
    "description": "الأستاذ الفاضل الاعلامي القدير \nجميل محمود عزالدين حفظه الله ورعاه  ظهرت هذه الايام. الحاسدين. والمسلطين اقلام الحسد ضده وانه فاسد وانه اخوه معه بيت وسياره وفلوس. شعب تعود على الحسد والمرض والقيل لن...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/690763961_4417168421899076_805848398149374876_n.jpg?stp=dst-jpg_tt6&cstp=mx720x664&ctp=p600x600&_nc_cat=106&ccb=1-7&_nc_sid=b96d88&_nc_ohc=CNzMQ1SU0XwQ7kNvwEYPDM8&_nc_oc=AdogyVGxQkOuE6NAoRwn6Up8AVa1ZItBzd_SVdBak0bCvR9SY9vu3uc_baWguRtWo-0&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=Jc-XDAtMrOKotT_rgTxRgw&_nc_ss=7f289&oh=00_Af6a9nnyh3A0CGXEjPOYMD_elynNglVFkG9OQSc3miiBsQ&oe=6A0DA95E",
    "available": true
  },
  {
    "id": 14,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1GCpMEkCvA/",
    "canonicalUrl": "https://www.facebook.com/alsabahiyemen/posts/%D8%AC%D9%85%D9%8A%D9%84-%D8%B9%D8%B2-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%A3%D9%8A%D9%82%D9%88%D9%86%D8%A9-%D8%A7%D9%84%D8%B4%D8%AC%D8%A7%D8%B9%D8%A9-%D9%88%D8%B6%D9%85%D9%8A%D8%B1-%D8%A7%D9%84%D9%88%D8%B7%D9%86%D9%86%D8%A4%D9%83%D8%AF-%D8%AA%D8%B6%D8%A7%D9%85%D9%86%D9%86%D8%A7-%D8%A7%D9%84%D9%85%D8%B7%D9%84%D9%82-%D9%88%D9%88%D9%82%D9%88%D9%81%D9%86%D8%A7-%D8%A7%D9%84%D8%AB%D8%A7%D8%A8%D8%AA-%D9%85%D8%B9-%D9%85%D9%86/27320301394253882/",
    "title": "أحمد الصباحي",
    "description": "جميل عز الدين أيقونة الشجاعة وضمير الوطن.\nنؤكد تضامننا المطلق ووقوفنا الثابت مع من جعل الشرف الوطني بوصلته الوحيدة.",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/689861758_27320225874261434_2890219879435376644_n.jpg?stp=dst-jpg_tt6&cstp=mx640x1302&ctp=p600x600&_nc_cat=101&ccb=1-7&_nc_sid=b96d88&_nc_ohc=wwDQHpb5RPAQ7kNvwGeIsJC&_nc_oc=AdrtyAaauyAdLS3tHTUi_iOaafDMVR-C604KT84rwJj9sSpPTbet9VsvjutbNI-1Mn4&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=TXXfQNwU2yqUiOn1NOLsXA&_nc_ss=7f289&oh=00_Af6WmWxEwvUAUW0UnquBvOz0KwvszO_h79Hx73X0rEHL7w&oe=6A0D8927",
    "available": true
  },
  {
    "id": 15,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1JPEVA6emw/",
    "canonicalUrl": "https://www.facebook.com/mhmd.rshad.alwhyby/posts/%D9%84%D9%85-%D9%8A%D8%B9%D8%B1%D9%81%D9%88%D8%A7-%D9%83%D9%8A%D9%81-%D9%8A%D8%B9%D9%8A%D8%A8%D9%88%D9%87-%D9%81%D9%82%D8%A7%D9%84%D9%88%D8%A7%D8%B9%D8%AC%D8%B2%D9%88%D8%A7-%D8%B9%D9%86-%D9%85%D9%8F%D8%A8%D8%A7%D8%B1%D8%B2%D8%AA%D9%87-%D9%81%D9%8A-%D9%85%D9%8A%D8%AF%D8%A7%D9%86-%D8%A7%D9%84%D8%AD%D9%8F%D8%AC%D8%A9-%D9%81%D8%A7%D8%B1%D8%AA%D8%AF%D9%91%D9%88%D8%A7-%D8%AE%D8%A7%D8%A6%D8%A8%D9%8A%D9%86-%D8%A5%D9%84%D9%89/1624244595929033/",
    "title": "محمد رشاد الوهيبي",
    "description": "\"لم يعرفوا كيف يعيبوه، فقالوا..!\n«عجزوا عن مُبارزته في ميدان الحُجة، فارتدّوا خائبين إلى أزقة الهمز واللمز؛ فالعاجزُ حين تُقهر حُجته، ويجفّ مَعين منطقِه، لا يجدُ مَلاذاً سوى الانحدار إلى سفاسف القول....",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/688940023_1624244572595702_1971355406454530222_n.jpg?stp=dst-jpg_tt6&cstp=mx945x1251&ctp=p600x600&_nc_cat=108&ccb=1-7&_nc_sid=b96d88&_nc_ohc=Ugp4Sz0tzRoQ7kNvwHAN41b&_nc_oc=AdqP_yLNIeegt0OgWzEDcK1vIeMdy3J5hIkbUMOtduD9IVFeFeZn7dGUUS76TJd8WOY&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=sG-pX9OVb2A0n4BXXAIPag&_nc_ss=7f289&oh=00_Af4phKNLITQPrtF0xkryrX1LEWQoCx-5tXeOpcMuRIKG5A&oe=6A0D80F7",
    "available": true
  },
  {
    "id": 16,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1Aq6wa2qiw/",
    "canonicalUrl": "https://www.facebook.com/moh.alhamiidi/posts/%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%87%D8%A7%D9%85%D8%A9-%D9%88%D9%82%D8%A7%D9%85%D8%A9-%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D9%88%D8%B7%D9%86%D9%8A%D8%A9-%D9%88%D9%85%D9%86-%D8%A3%D8%A8%D8%B1%D8%B2-%D9%88%D8%AC%D9%88%D9%87-%D8%A7%D9%84%D8%B4%D8%A7%D8%B4%D8%A9-%D8%A7%D9%84%D9%8A%D9%85%D9%86%D9%8A%D8%A9/2417871905355346/",
    "title": "محمد عبدالرحمن الحميدي",
    "description": "الأستاذ جميل محمود عزالدين هامة وقامة إعلامية وطنية، ومن أبرز وجوه الشاشة #اليمنية خلال سنوات عدة، كان إلى جانب الدولة والجمهورية منذ الوهلة الأولى، يعمل في ظل إمكانيات شحيحة، وميزانيات تكاد تكون...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/686934024_2417871878688682_822272827617153299_n.jpg?stp=dst-jpg_tt6&cstp=mx1628x1440&ctp=p600x600&_nc_cat=107&ccb=1-7&_nc_sid=b96d88&_nc_ohc=Y71R-gXgf54Q7kNvwETSNrc&_nc_oc=AdpCilvPHZ6e-8WSoRctI67Ojdn5SELSXWqUOSMNXYMT6Aa78pM5JdcOOpyAeSZ4cEw&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=3zVMTpBc2pROC8mGiL_n9A&_nc_ss=7f289&oh=00_Af4x8aDLT_AUezITMJ9B_8Fdp3PV5ho4tcmY-V0zEHgA7w&oe=6A0D9A6E",
    "available": true
  },
  {
    "id": 17,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1bsvE2VGg8/",
    "canonicalUrl": "https://www.facebook.com/Mohammed774542424/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%B9%D8%B1%D9%81%D9%86%D8%A7-%D9%88%D8%B7%D9%86%D9%8A%D8%AA%D9%87-%D9%88%D8%AD%D8%A8%D9%87-%D9%84%D8%A8%D9%84%D8%A7%D8%AF%D9%87-%D9%88%D8%B3%D9%85%D8%B9%D9%86%D8%A7-%D8%B5%D9%88%D8%AA%D9%87-%D9%88%D9%83%D9%84%D9%85%D8%AA-%D8%A7%D9%84%D8%AD%D9%82-%D9%85%D9%86-%D9%84%D8%B3%D8%A7%D9%86%D9%87-%D9%81%D9%8A-%D9%88/122250771776308621/",
    "title": "محمد عبدالملك اليوسفي",
    "description": "جميل محمود عزالدين عرفنا وطنيته وحبه لبلاده وسمعنا صوته وكلمت الحق من لسانه في وجه الحوسي ووجه مليسيات الإمارات \nلم نسمع منه الا كل خير سلاحه وواجهته نحو الحوسي ولم يقدح بي عر.. ض احد \nهذا ماعرفت عنه...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/690611930_122250771752308621_730865611444082946_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=100&ccb=1-7&_nc_sid=b96d88&_nc_ohc=JNeUM7ed5UgQ7kNvwGhtpiv&_nc_oc=AdqDIA2M6AQAx_kiowM8f7tmCDgwCC0e_fEuQPhcb7tEFbQafO_QuhENxhZl5TaG-pQ&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=RuuYfYHgctbDuy5fd2OOIA&_nc_ss=7f289&oh=00_Af6bPJ-kaySVa6xIW_ZYRwyVeQYwMVnZfJStM6KZUO_f8g&oe=6A0D82B7",
    "available": true
  },
  {
    "id": 18,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1bXYNWcHtL/",
    "canonicalUrl": "https://www.facebook.com/share/1bXYNWcHtL/",
    "title": "",
    "description": "",
    "image": "",
    "available": false
  },
  {
    "id": 19,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18gsWAAsXV/",
    "canonicalUrl": "https://www.facebook.com/share/18gsWAAsXV/",
    "title": "",
    "description": "",
    "image": "",
    "available": false
  },
  {
    "id": 20,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1LCuheyr6s/",
    "canonicalUrl": "https://www.facebook.com/alqyl.fysl.alsh.wry.alsh.wry/posts/%D9%86%D9%82%D8%B7%D8%A9_%D9%86%D8%B8%D8%A7%D9%85_%D9%88%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD_%D9%85%D9%81%D8%A7%D9%87%D9%8A%D9%85-%D9%88%D9%83%D9%84%D9%85%D8%A9-%D8%AD%D9%82-%D9%8A%D8%AC%D8%A8-%D8%A3%D9%86-%D8%AA%D9%8F%D9%82%D8%A7%D9%84-%D9%84%D8%A3%D9%86-%D8%A7%D9%84%D8%B5%D9%85%D8%AA-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D9%84%D9%8A%D8%B3-%D8%AE%D8%B0%D9%84%D8%A7%D9%86%D9%8B%D8%A7-%D9%81%D9%82%D8%B7-%D9%88%D8%A5/122272180004216402/",
    "title": "فيصل الشعوري الشعوري",
    "description": "*#نقطة_نظام_وتصحيح_مفاهيم*  \nوكلمة حق يجب أن تُقال، لأن الصمت اليوم ليس خذلانًا فقط، وإنما خيانة مكتملة الأركان.  \nــــــــــــــــــــــــــــــــــــــــــــ\nلا أعرف #مجلي_الصمدي، ولكني أعرف جميل...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/690870786_122272179968216402_2156452392953497465_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=111&ccb=1-7&_nc_sid=b96d88&_nc_ohc=O2fQMHyCH20Q7kNvwFxDwC_&_nc_oc=Adqqbm7QWemBSRkCMPAeMaFIdwLgBBH5bjOA_sTgBQ2kzRX7KnNh-_10ntyVffnAN9k&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=ZslxIhLO2cywCzgsYBNRkQ&_nc_ss=7f289&oh=00_Af5lbfaX3UTGC9ahnM701aoZ3X-QfgfdJVZ6nXyLsazU8w&oe=6A0D8955",
    "available": true
  },
  {
    "id": 21,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18U831WbQ4/",
    "canonicalUrl": "https://www.facebook.com/100009338670352/posts/%D8%A7%D9%84%D8%A7%D8%AE%D8%AA%D9%84%D8%A7%D9%81-%D9%85%D8%B9-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AD%D9%82-%D9%85%D9%83%D9%81%D9%88%D9%84-%D9%84%D9%83%D9%86-%D8%AA%D8%AD%D9%88%D9%8A%D9%84-%D8%A7%D9%84%D9%86%D9%82%D8%AF-%D8%A5%D9%84%D9%89-%D8%A5%D8%B3%D8%A7%D8%A1%D8%A9-%D8%B4%D8%AE%D8%B5%D9%8A%D8%A9-%D9%88%D8%A7%D8%AA%D9%87%D8%A7%D9%85%D8%A7%D8%AA/4455806328073946/",
    "title": "ابو يحي سليمان",
    "description": "الاختلاف مع جميل محمود عزالدين  حق مكفول، لكن تحويل النقد إلى إساءة شخصية واتهامات بالتسلق والتنطع لا يخدم أحد، خصوصًا عندما نتحدث عن شخص له تاريخ إعلامي وحضور معروف.\n\nجميل قد تتفق أو تختلف معه، لكن...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/691607310_982575281091338_2406927203322018541_n.jpg?stp=dst-jpg_tt6&cstp=mx521x1156&ctp=s521x1156&_nc_cat=103&ccb=1-7&_nc_sid=cae128&_nc_ohc=rnCaXEmyzhsQ7kNvwFz-QsU&_nc_oc=AdqdEQ5sXCihhwc5Ei4x1zBQ-wXa6-BWlnEZD08e9nBO16fSbBA8DzrvlUqdgCAW9NE&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=IMNKcFF3EwERntJsz47T5g&_nc_ss=7f289&oh=00_Af7hYdRsfJfjPGwmtzm2X0AYWQ8hDc_nJF9U_cPEQ7nYwg&oe=6A0D9F4C",
    "available": true
  },
  {
    "id": 22,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1GQRwLRn3L/",
    "canonicalUrl": "https://www.facebook.com/kmal.mhmd.alb.dany/posts/%D9%87%D8%A8%D8%B7%D8%AA-%D8%A8%D8%B9%D9%88%D8%B6%D8%A9-%D8%B9%D9%84%D9%89-%D9%86%D8%AE%D9%84%D8%A9-%D9%81%D9%84%D9%85%D8%A7-%D8%A7%D8%B1%D8%A7%D8%AF%D8%AA-%D8%A7%D9%86-%D8%AA%D8%B7%D9%8A%D8%B1-%D9%82%D8%A7%D9%84%D8%AA-%D9%84%D9%84%D9%86%D8%AE%D9%84%D8%A9-%D8%AA%D9%85%D8%A7%D8%B3%D9%83%D9%8A-%D8%A3%D9%8A%D8%AA%D9%87%D8%A7-%D8%A7%D9%84%D9%86%D8%AE%D9%84%D8%A9-%D9%81%D8%A3%D9%86%D8%A7-%D8%B3%D9%88%D9%81-/2794017204301657/",
    "title": "كمال محمد البعداني",
    "description": "هبطت بعوضة على نخلة ، فلما ارادت ان تطير قالت للنخلة ؛ تماسكي أيتها النخلة ، فأنا سوف اطير ! فضحكت النخلة وقالت للبعوضة : والله ما شعرت بك يوم وقعت  فكيف أشعر بك اذا طرت ؟ فلا تلفت لطنين البعوض يا...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/696005598_2793994164303961_3473060185864530094_n.jpg?stp=cp6_dst-jpg_tt6&cstp=mx996x662&ctp=p600x600&_nc_cat=110&ccb=1-7&_nc_sid=b96d88&_nc_ohc=gKBn8kTjXzIQ7kNvwG12DfI&_nc_oc=Adp7noRk7gLVKvTTmjaUj5ZrqVox6-5GkxTnXg-KT57mueyQ0EV3Myv5Rg7gin8bFTk&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=s1nTzZhDs8FwVLYkquPRAQ&_nc_ss=7f289&oh=00_Af6JvfEMkAzYvF8iTvSolQHncUlz1BVzlGnsHcUuX1xjvg&oe=6A0D8546",
    "available": true
  },
  {
    "id": 23,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1D2My2SzNj/",
    "canonicalUrl": "https://www.facebook.com/alqyl.fysl.alsh.wry.alsh.wry/posts/%D9%8A%D9%85%D9%86%D9%8A-%D8%A7%D9%84%D8%A3%D8%B5%D9%84-%D9%87%D8%B0%D8%A7-%D9%86%D8%B3%D8%A8%D9%8A%D9%82%D8%AF-%D8%AD%D8%A8%D8%A7%D9%86%D8%A7-%D8%A7%D9%84%D9%84%D9%87-%D8%A3%D8%B9%D9%84%D9%89-%D8%A7%D9%84%D8%B1%D8%AA%D8%A8%D9%90%D8%A3%D9%8A-%D8%A3%D8%AE-%D8%B9%D9%84%D9%85%D8%A7%D9%8B-%D9%88%D9%85%D8%A7-%D9%8A%D8%AF%D8%B1%D9%8A%D9%83-%D9%85%D9%86-%D9%8A%D8%B1%D8%AA%D9%82%D9%8A-%D8%A7%D9%84%D8%B9%D8%B1%D8%B4/122272361660216402/",
    "title": "فيصل الشعوري الشعوري",
    "description": "­يمني الأصل هذا نسبي\nقد حبانا الله أعلى الرتبِ\n\nأي أخ علماً وما يدريك من\n يرتقي العرش وهام السحبِ\n\nهكذا جئنا وفي أقدارنا \nأن نكون الرأس دون الذنبِ\n\nيمنيٌ جئت من أرض سبأ\nأحمل الحق بأسمى الكتبِ\n\nلا تسل...",
    "image": "",
    "available": true
  },
  {
    "id": 24,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1apimmLbgC/",
    "canonicalUrl": "https://www.facebook.com/ALSlahi.Abdullh.YEM/posts/%D8%A7%D9%84%D8%AA%D9%84%D9%81%D8%B2%D9%8A%D9%88%D9%86-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A-%D8%AD%D9%8A%D9%86-%D9%8A%D8%B5%D8%A8%D8%AD-%D8%A7%D9%84%D8%B5%D9%88%D8%AA-%D9%87%D8%AF%D9%81%D8%A7%D8%AF%D8%B9%D9%88%D9%86%D8%A7-%D9%86%D9%82%D8%B1%D8%A3-%D8%A8%D9%85%D9%88%D8%B6%D9%88%D8%B9%D9%8A%D8%A9-%D8%A7%D9%84%D8%AD%D9%85%D9%84%D8%A9-%D8%A7%D9%84%D9%85%D9%85%D9%86%D9%87%D8%AC%D8%A9-%D8%B6%D8%AF-%D8%A7%D9%84%D8%A3%D8%B3%D8%AA/2865211433822125/",
    "title": "عبدالله الصلاحي",
    "description": "التلفزيون الرسمي… حين يصبح الصوت هدفا\n\nدعونا نقرأ بموضوعية الحملة الممنهجة ضد الأستاذ جميل عز الدين\nاولا نتفق على ان التلفزيون الرسمي هو العنوان الأوضح لصوت الدولة والمرآة التي تعكس موقفها وخياراتها...",
    "image": "",
    "available": true
  },
  {
    "id": 25,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/v/1J42npMiKG/",
    "canonicalUrl": "https://www.facebook.com/reel/4267382486909465/",
    "title": "‏‏١٢٢ ألف‏ مشاهدة‏ · ‏‏٨٫٤ ألف‏ تفاعل‏ | سلام عليكم وعلى قلوبكم النقية وعلى أرواحكم الزكية وعلى أقلامكم الصادقة ومواقفكم النبيلة والثابتة لقد غمرتني محبتكم وثقتكم وزادتني ثقة وثباتا فعاجز أنا عن شكركم وعن رد الجميل وأسأل الله تعالى أن يجعلني عند حسن ظنكم بي إنه قادر على ذلك \nوالتحية لكل كريم نفس ولكل حر جمهوري مهما أختلفنا معه ومهما أخطأ في حقنا يبقى جمهوري يرفض السلالة ويرفض الخنوع لها ولم يخدمها أو يشارك في جرائمها أو خان الجمهورية \nالشاعر اليمني المميز وليد الشواقبة\n\n. | جميل محمود عزالدين",
    "description": "سلام عليكم وعلى قلوبكم النقية وعلى أرواحكم الزكية وعلى أقلامكم الصادقة ومواقفكم النبيلة والثابتة لقد غمرتني محبتكم وثقتكم وزادتني ثقة وثباتا فعاجز أنا عن شكركم وعن رد الجميل وأسأل الله تعالى أن...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t15.5256-10/699084033_1334675955230540_1723256703170317078_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=a27664&_nc_ohc=U5NZQ4P_VicQ7kNvwETFfNc&_nc_oc=AdrMzMpQcv_bGc_-AjRlA0I1b_PL4hmQoK3_uqUmr8yHnN4qbfqWF3Zv3BMkkc8-U-c&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=7Z5R-KGoHZuF6t3f_wzhpw&_nc_ss=7f289&oh=00_Af5I9A6qn3ri6EVf2GWkQOoS-cfzmUh7WPQA3powx-EYzg&oe=6A0D9DB5",
    "available": true
  },
  {
    "id": 26,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1CbTUqkrLx/",
    "canonicalUrl": "https://www.facebook.com/skhr.al.lqmy/posts/%D8%A3%D8%AC%D9%85%D9%84_%D8%B4%D8%AE%D8%B5%D9%8A%D8%A9_%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D8%A7%D9%84%D8%B4%D8%A7%D8%B9%D8%B1-%D8%A7%D9%84%D8%A3%D8%AF%D9%8A%D8%A8-%D8%A3-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AD%D9%8A%D9%86-%D9%8A%D9%83%D9%88%D9%86-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85-%D8%B6%D9%85%D9%8A%D8%B1%D9%8B%D8%A7-%D9%88%D8%AD/1291186226238182/",
    "title": "صخر العلقمي",
    "description": "#أجمل_شخصية_إعلامية 🥰\nالشاعر الأديب أ. جميل محمود عزالدين \nحين يكون الإعلام ضميرًا وحين تتحول الكلمة إلى موقف\nوحين يصبح الحرف سلاح كل حر نعرف أننا أمام قامة لا تُقاس إلا بالوطن الأستاذ جميل محمود...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/624259571_1291186149571523_2122574357061145652_n.jpg?stp=dst-jpg_tt6&cstp=mx1280x720&ctp=p600x600&_nc_cat=104&ccb=1-7&_nc_sid=b96d88&_nc_ohc=kMArlDAdwoQQ7kNvwHo5KzM&_nc_oc=AdqZweOm-17ZXHLhslgATYlcCH97N7nWmFpmevpZmIHYxDhPvwn-zbTD99C_HHxd5rU&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=kogXDIs7QZuxSRnQ889Tng&_nc_ss=7f289&oh=00_Af4EIVQG8EAKP3_yHUTmKNNTxJHV9hnV7OX6KlD-qJBA2A&oe=6A0D7868",
    "available": true
  },
  {
    "id": 27,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1UNtH5URe9/",
    "canonicalUrl": "https://www.facebook.com/100009399148430/posts/%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A-%D8%AC%D9%85%D9%8A%D9%84-%D8%B9%D8%B2-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%A3%D8%AD%D8%AF-%D8%A3%D8%A8%D8%B1%D8%B2-%D8%A7%D9%84%D8%B1%D9%85%D9%88%D8%B2-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D8%A7%D9%84%D9%85%D9%86%D8%AD%D8%AF%D8%B1%D8%A9-%D9%85%D9%86-%D9%85%D8%AD%D8%A7%D9%81%D8%B8%D8%A9-%D8%A5%D8%A8%D9%88%D8%B1%D8%BA%D9%85-%D8%A7%D9%84%D8%AA%D8%A8%D8%A7/4408480232808571/",
    "title": "محمد الوايلي",
    "description": "الإعلامي جميل عز الدين أحد أبرز الرموز الإعلامية المنحدرة من محافظة إب،ورغم التباينات الحزبية أو الرؤى السياسية التي قد تفرق البعض حوله، إلا أن هناك إجماعاً على كونه قامَة إعلامية قديرة. يمتلك...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t39.30808-6/621217108_4408478276142100_2166769029897238606_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=111&ccb=1-7&_nc_sid=b96d88&_nc_ohc=R27aCGq-2YQQ7kNvwFZnMj-&_nc_oc=AdrL1ATRBYCMnpyTK6S5WYk8m-F69dcuiXTsbce7qL8PzWJ43Zx40jugeZ8TtOUwkiY&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=WGzMSOP3LKSoS2UcZUFY2g&_nc_ss=7f289&oh=00_Af75ujie03YmG3sW7euo7JWASonbroDewGPgiVOF2RLicQ&oe=6A0D973C",
    "available": true
  },
  {
    "id": 28,
    "type": "twitter",
    "sourceUrl": "https://x.com/yemenscopsa/status/2017011455686541322",
    "canonicalUrl": "https://x.com/yemenscopsa/status/2017011455686541322",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @yemenscopsa على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 29,
    "type": "twitter",
    "sourceUrl": "https://x.com/yemenp5jq/status/2017033738316660864",
    "canonicalUrl": "https://x.com/yemenp5jq/status/2017033738316660864",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @yemenp5jq على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 30,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1GZg4QheZ8/",
    "canonicalUrl": "https://www.facebook.com/bn.hmwd.912074/posts/%D8%B3%D9%8A%D8%A8%D9%82%D9%8A-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%83%D8%A8%D9%8A%D8%B1-%D8%A8%D9%82%D9%84%D9%88%D8%A8%D9%86%D8%A7-%D9%88%D8%B9%D9%8A%D9%88%D9%86%D9%86%D8%A7-%D9%83-%D9%88%D8%B7%D9%86%D9%86%D8%A7-%D8%A7%D9%84%D9%83%D8%A8%D9%8A%D8%B1-%D8%A7%D9%84%D8%B9%D8%B8%D9%8A%D9%85-%D8%B3%D9%8A%D8%A8/1631368884871222/",
    "title": "بن حمود",
    "description": "سيبقي الإعلامي  جميل محمود عزالدين \nكبير بقلوبنا وعيوننا ك وطننا الكبير العظيم \nسيبقي هو صوت الوطن والمواطن وسيبقي \nهو ناطق الجيش والأمن حتى وإن لم يكون هناك \nقرار رسمي من الرئاسة سيبقي هو ذلك الذي...",
    "image": "https://scontent.flhr9-1.fna.fbcdn.net/v/t15.5256-10/638061497_2170769870397685_9099313468204081355_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=a27664&_nc_ohc=nXeDXtLqYn0Q7kNvwHUKSgm&_nc_oc=AdpOkCkWHE1hz3V6xFjXrkDOHtVFyepnefFZRxtgPyClBvW1_CC6QkKkopO43DNmOxM&_nc_zt=23&_nc_ht=scontent.flhr9-1.fna&_nc_gid=Al8bKjPsXHb7Sr8B7RuBJA&_nc_ss=7f289&oh=00_Af6mKNvd2eqQSF7bYBNyhF27Tk_TpaH4MUfY53mOeGAKVQ&oe=6A0D89D1",
    "available": true
  },
  {
    "id": 31,
    "type": "twitter",
    "sourceUrl": "https://x.com/albtool_3/status/2023885789713592777",
    "canonicalUrl": "https://x.com/albtool_3/status/2023885789713592777",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @albtool_3 على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 32,
    "type": "twitter",
    "sourceUrl": "https://x.com/holand_ye/status/2036374687127666785",
    "canonicalUrl": "https://x.com/holand_ye/status/2036374687127666785",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @holand_ye على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 33,
    "type": "twitter",
    "sourceUrl": "https://x.com/drabusaad/status/2036194360027390259",
    "canonicalUrl": "https://x.com/drabusaad/status/2036194360027390259",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @drabusaad على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 34,
    "type": "twitter",
    "sourceUrl": "https://x.com/salemalsehman/status/2036357614955630893",
    "canonicalUrl": "https://x.com/salemalsehman/status/2036357614955630893",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @salemalsehman على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 35,
    "type": "twitter",
    "sourceUrl": "https://x.com/yahyaa12a/status/2036523299291721812",
    "canonicalUrl": "https://x.com/yahyaa12a/status/2036523299291721812",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @yahyaa12a على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 36,
    "type": "twitter",
    "sourceUrl": "https://x.com/a_alomari_0505/status/2036628027103199303",
    "canonicalUrl": "https://x.com/a_alomari_0505/status/2036628027103199303",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @a_alomari_0505 على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 37,
    "type": "twitter",
    "sourceUrl": "https://x.com/n_b52otb/status/2036528386818953389",
    "canonicalUrl": "https://x.com/n_b52otb/status/2036528386818953389",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @n_b52otb على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 38,
    "type": "twitter",
    "sourceUrl": "https://x.com/yemenscopsa/status/2036648696381612222",
    "canonicalUrl": "https://x.com/yemenscopsa/status/2036648696381612222",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @yemenscopsa على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 39,
    "type": "twitter",
    "sourceUrl": "https://x.com/ksa2012f/status/2036821280733716816",
    "canonicalUrl": "https://x.com/ksa2012f/status/2036821280733716816",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @ksa2012f على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 40,
    "type": "twitter",
    "sourceUrl": "https://x.com/c0olo/status/2037267828928041181",
    "canonicalUrl": "https://x.com/c0olo/status/2037267828928041181",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @c0olo على منصة X",
    "image": "",
    "available": true
  },
  {
    "id": 41,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/1727010673/posts/10203175110575073/",
    "canonicalUrl": "https://www.facebook.com/samgh4u/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%84%D9%8A%D8%B3-%D9%87%D8%A7%D8%B4%D9%85%D9%8A%D9%8B%D8%A7-%D9%88%D9%84%D8%A7-%D8%B3%D9%84%D8%A7%D9%84%D9%8A%D9%8B%D8%A7-%D8%AC%D9%85%D9%8A%D9%84-%D9%82%D9%84%D8%A8%D9%8C-%D8%AD%D8%B1-%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A-%D8%B3%D8%A7%D8%B7%D8%B9-%D8%A8%D9%84%D8%AF%D9%88%D8%B2%D8%B1-%D9%84%D8%A7-%D9%8A%D8%AA/10203175110575073/",
    "title": "سام الغباري",
    "description": "جميل محمود عزالدين ليس هاشميًا ولا سلاليًا ، جميل قلبٌ حر ، جمهوري ساطع ، بلدوزر لا يتوقف عن هدم خرافة آل البيت ، وإثارة الرعب في قلوب المتمردين .\n- نحن بحاجة هذا الرجل الغاضب ، القادة الذين لا...",
    "image": "",
    "available": true
  }
];
