// AUTO-GENERATED by scripts/fetch-social-content.mjs — do not edit by hand.
// Regenerate with: node scripts/fetch-social-content.mjs
// Last fetch: 2026-05-15T21:01:13.717Z

export interface SocialPost {
  id: number;
  type: 'facebook' | 'twitter';
  sourceUrl: string;
  canonicalUrl: string;
  title: string;
  description: string;
  image: string;
}

export const SOCIAL_POSTS: SocialPost[] = [
  {
    "id": 1,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/18GvVs4K8V/",
    "canonicalUrl": "https://www.facebook.com/saad.alasaal.2025/posts/%D9%85%D8%B9%D8%B1%D9%81%D8%AA%D9%8A-%D8%A8%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%85%D9%86%D8%B0-%D8%B9%D8%A7%D9%85-2018-%D8%B9%D9%85%D9%84%D8%A7%D9%82-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85-%D8%A7%D9%84%D9%8A%D9%85%D9%86%D9%8A-%D9%84%D9%8A%D8%B3-%D9%85%D8%B9%D8%B1%D9%81%D8%A9-%D8%B4/2483806965378169/",
    "title": "ابووقاص سعد",
    "description": "معرفتي بالأستاذ جميل محمود عزالدين منذ عام 2018 عملاق الإعلام اليمني ليس معرفة شخصية بل معرفة من الفضاء الرقمي على منصة #الفيسبوك ومن منصة #X تويتر سابقاً وجدته انا وغير من الناشطين والإعلاميين...",
    "image": "https://scontent-lhr8-1.xx.fbcdn.net/v/t39.30808-6/688822577_2483806932044839_4435052656455459486_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=111&ccb=1-7&_nc_sid=b96d88&_nc_ohc=JbseOtf9_xIQ7kNvwFh34_W&_nc_oc=Adr7BrBm4exSaPkj-87kQ1OplLOxi9jYa7BfQO9TUCnxCxdmQjncJAmn5Ro7Bzx3z1FUtKaJbK-DeHDxNXYRTpYz&_nc_zt=23&_nc_ht=scontent-lhr8-1.xx&_nc_gid=Z1-oHgsPvUYQ3-a1Zh_YHQ&_nc_ss=7f289&oh=00_Af6uzdaJrdycKtOGbc6-i6LniM1b2Wyr89a_DxMiM6WcuA&oe=6A0D6A7A"
  },
  {
    "id": 2,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/184gm31REJ/",
    "canonicalUrl": "https://www.facebook.com/ALSlahi.Abdullh.YEM/posts/%D9%82%D8%A7%D9%84%D9%88%D8%A7-%D8%B9%D8%AC%D8%B2%D8%AA-%D8%A7%D9%84%D8%B1%D8%AF-%D8%B9%D8%A7%D9%84%D9%84%D9%8A-%D9%8A%D8%B3%D8%A8%D9%88%D9%83%D8%A7%D9%88-%D8%AE%D9%81%D9%80%D8%AA-%D9%85%D9%86-%D8%B1%D8%AF%D9%83-%D8%AA%D8%B2%D9%8A%D8%AF-%D8%A7%D9%84%D8%B4%D8%AA%D8%A7%D9%8A%D9%80%D9%85%D8%B1%D8%AF%D9%8A%D8%AA-%D9%85%D8%A7%D9%87%D9%88-%D8%B9%D8%AC%D8%B2-%D9%81%D9%8A-%D8%A7%D9%84%D8%B1%D8%AF-%D9%8A%D8%A7%D8%A8/2862325527444049/",
    "title": "عبدالله الصلاحي",
    "description": "قالوا عجزت الرد عاللي يسبوك\nاو خفـت من ردك تزيد الشتايـم\n\nرديت ماهو عجز في الرد يابوك\nلكن ذكرت اني بـن الحـاج سالـم\n\nوش قول له لوقال لي كيف وطوك\nمن حصن في راس الجبل للتهايم\n\nونسيت اصل اللي على العز...",
    "image": "https://scontent-lhr8-2.xx.fbcdn.net/v/t39.30808-6/687039779_2862325494110719_3179473297691848628_n.jpg?stp=dst-jpg_tt6&cstp=mx540x960&ctp=s540x960&_nc_cat=103&ccb=1-7&_nc_sid=b96d88&_nc_ohc=mkLP6XE4xj0Q7kNvwGg9yQg&_nc_oc=Adri-GPuUwkEGm0s7IhEQeyyk-NZWjOEl2InnabRblSAL8Ypt3K4IGrGIWEhZSn461XNz8T6yYf6klXgKeLe7Ac0&_nc_zt=23&_nc_ht=scontent-lhr8-2.xx&_nc_gid=Qnz7d1XWCLNQ0mcqoyvmhA&_nc_ss=7f289&oh=00_Af7xo_8B8v6VFlZX4amRlo-hxrjTclAeYrjrIgd6emJ5wA&oe=6A0D4AAD"
  },
  {
    "id": 3,
    "type": "twitter",
    "sourceUrl": "https://x.com/g_khamre/status/2050969680458727691",
    "canonicalUrl": "https://x.com/g_khamre/status/2050969680458727691",
    "title": "منشور على X (تويتر)",
    "description": "منشور رسمي من حساب @g_khamre على منصة X",
    "image": ""
  },
  {
    "id": 4,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1FWdCCXQ8p/",
    "canonicalUrl": "https://www.facebook.com/MoneerAlhaj2030/posts/%D9%87%D9%84-%D9%8A%D8%B3%D8%AA%D9%88%D9%8A-%D8%B5%D9%88%D8%AA-%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9-%D9%88%D9%84%D8%B3%D8%A7%D9%86-%D8%A7%D9%84%D9%88%D8%B7%D9%86-%D8%A7%D9%84%D9%81%D8%B5%D9%8A%D8%AD-%D8%B0%D9%84%D9%83-%D8%A7%D9%84%D8%B3%D9%8A%D9%81-%D8%A7%D9%84%D9%85%D8%B4%D8%B1%D8%B9-%D9%81%D9%8A-%D9%88%D8%AC%D9%87-%D8%A7%D9%84%D8%B9%D8%AA%D9%85%D8%A9-%D9%88%D9%84%D8%B3%D8%A7%D9%86-%D8%A7/4450708078495138/",
    "title": "منير الحاج",
    "description": "هل يستوي صوت الجمهورية ولسان الوطن الفصيح، ذلك السيف المشرع في وجه العتمة، ولسان الوطن إذا نطق أنبت المعنى وأورق الحقيقة، وحامل جرح اليمن كقنديل لا ينطفئ في ريح النكبات، مع من ٲضاع بوصلته، و باع صوته...",
    "image": ""
  },
  {
    "id": 5,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1B2KJQvpE3/",
    "canonicalUrl": "https://www.facebook.com/100007677948905/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%84%D9%8A%D8%B3-%D9%85%D8%B8%D8%B7%D8%B1%D8%A7-%D9%84%D9%84%D8%AA%D8%B9%D8%B1%D9%8A%D9%81-%D8%A8%D9%86%D9%81%D8%B3%D9%87%D9%81%D8%AC%D8%A8%D8%A7%D9%84-%D8%A7%D9%84%D9%8A%D9%85%D9%86-%D9%88%D8%B3%D9%87%D9%88%D9%84%D9%87%D8%A7-%D9%88%D9%87%D8%B6%D8%A7%D8%A8%D9%87%D8%A7-%D9%88%D8%AA%D9%84%D8%A7%D9%84%D9%87%D8%A7-%D9%88/4393753657557189/",
    "title": "وحيد وغريب",
    "description": "جميل محمود عز الدين ليس مظطرا للتعريف بنفسه\nفجبال اليمن وسهولها وهضابها وتلالها وأشجارها وأحجارها و شطانها وبحارها يعرفونه ويعرفون من هو جميل عز الدين\n\nيعرفه جن اليمن  وإنسها أمواتها وأحيائها \nيعرفه...",
    "image": ""
  },
  {
    "id": 6,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18Pvuaraqb/",
    "canonicalUrl": "https://www.facebook.com/share/18Pvuaraqb/",
    "title": "",
    "description": "",
    "image": ""
  },
  {
    "id": 7,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18XFqsHok9/",
    "canonicalUrl": "https://www.facebook.com/bdalrhmnalnmr.611808/posts/%D9%81%D9%8A-%D9%85%D9%8A%D8%AF%D8%A7%D9%86-%D8%A7%D9%84%D9%86%D8%B6%D8%A7%D9%84-%D8%A8%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A9-%D8%AA%D8%A8%D8%B1%D8%B2-%D9%85%D8%B9%D8%A7%D8%AF%D9%86-%D8%A7%D9%84%D8%B1%D8%AC%D8%A7%D9%84-%D9%81%D9%87%D9%86%D8%A7%D9%83-%D9%85%D9%86-%D9%8A%D8%B3%D9%83%D8%A8%D9%8F-%D8%AD%D8%A8%D8%B1%D9%87-%D8%AF%D9%85%D8%A7%D9%8B-%D9%88%D9%88%D9%81%D8%A7%D8%A1%D9%8B-%D9%84%D9%84%D9%88%D8%B7%D9%86-/26943116565376454/",
    "title": "عبد الرحمن النمر",
    "description": "في ميدان  النضال بالكلمة، تبرز معادن الرجال فهناك من يسكبُ حبره دماً ووفاءً للوطن ، وهناك من لا يتقنُ سوى رصِّ بضاعة الشتائم التي لا تُسمن ولا تُغني من وعي.\nإن الهجوم الذي يتعرض له القامة الإعلامية...",
    "image": "https://scontent-lhr6-1.xx.fbcdn.net/v/t39.30808-6/686959739_26943105655377545_7208997561526195808_n.jpg?stp=dst-jpg_tt6&cstp=mx1125x1251&ctp=p600x600&_nc_cat=102&ccb=1-7&_nc_sid=b96d88&_nc_ohc=2BbHi143BngQ7kNvwH0ZJ98&_nc_oc=AdrHYhqcufz8x6aXkrj66z0O-ppOB2IjJWwHh0t_N0nH4razID8dNgOJlKX9OsOsIokXmxSxzK5QTzvSw0r-n6kA&_nc_zt=23&_nc_ht=scontent-lhr6-1.xx&_nc_gid=Eh_9gLwdAZx-ivtyb4spEg&_nc_ss=7f289&oh=00_Af7PZijONrGs8lHizD61hha9xiDRRJ4gVBhXGdDgVX-i3Q&oe=6A0D5933"
  },
  {
    "id": 8,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18PER5LFQ1/",
    "canonicalUrl": "https://www.facebook.com/61573945325326/posts/%D9%84%D9%85-%D9%86%D8%AC%D8%AF-%D9%85%D9%86-%D8%A7%D9%84%D8%AD%D8%B1%D9%88%D9%81-%D9%85%D8%A7-%D9%8A%D9%83%D9%81%D9%8A-%D9%88%D9%84%D8%A7-%D9%85%D9%86-%D8%A7%D9%84%D9%83%D9%84%D9%85%D8%A7%D8%AA-%D9%85%D8%A7-%D9%8A%D9%88%D9%81%D9%8A-%D9%82%D8%AF%D8%B1%D9%83-%D9%8A%D8%A7-%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0%D9%86%D8%A7-%D8%A7%D9%84%D8%BA%D8%A7%D9%84%D9%8A-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88/122173282916798177/",
    "title": "ابو هجررران العلقمي الصبيحي",
    "description": "لم نجد من الحروف ما يكفي، ولا من الكلمات ما يوفي قدرك يا أستاذنا الغالي جميل محمود عزالدين \nفأنت لست مجرد إعلامي عابر، بل قيمة ثابتة، وهامة وطنية ارتفعت فوق كل محاولات التقليل والتشويه.\nأنت صوتٌ حين...",
    "image": "https://scontent-lhr6-1.xx.fbcdn.net/v/t15.5256-10/685936191_2173990483387528_5435028270101534370_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=a27664&_nc_ohc=v3dWYS_CAjwQ7kNvwHJn1_N&_nc_oc=Adp0u3DKN71AUyrwHcH6ibOkiKmwb9Od6iR-35L4xjCWW4AlZXNFTi0RVSuY2n6-BbOYZUziMTaaS8h43pMVOQdU&_nc_zt=23&_nc_ht=scontent-lhr6-1.xx&_nc_gid=TPyIUYuRUIm1WXYnxUlFVw&_nc_ss=7f289&oh=00_Af4aAsEgLygLcz2W4uspTPVYmfdO2UDF_ni2o5kfyDWjnQ&oe=6A0D6C22"
  },
  {
    "id": 9,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1EFZUNcdPR/",
    "canonicalUrl": "https://www.facebook.com/61561543972459/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%B5%D9%88%D8%AA-%D8%A7%D9%84%D8%AC%D9%85%D9%87%D9%88%D8%B1%D9%8A%D8%A9-%D9%88%D9%85%D8%AF%D9%81%D8%B9%D9%87%D8%A7-%D9%88%D8%B3%D9%8A%D9%81%D9%87%D8%A7-%D9%88%D8%AD%D8%A7%D8%B1%D8%B3-%D8%B1%D8%A7%D9%8A%D8%A9-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A%D9%85%D9%86%D8%B0-%D8%A7%D9%86%D9%82/122198630660384799/",
    "title": "ناجي القرطحي",
    "description": "جميل محمود عزالدين … صوت الجمهورية ومدفعها وسيفها، وحارس راية الإعلام الرسمي\n\nمنذ انقلاب الحوثي على الدولة، لم يكن الإعلامي جميل عزالدين مجرد اسم في شاشة أو صوت في نشرة؛ بل كان موقفًا واضحًا في زمن...",
    "image": "https://scontent-lhr6-2.xx.fbcdn.net/v/t39.30808-6/689324899_122198630504384799_2231402025815532837_n.jpg?stp=cp6_dst-jpg_tt6&cstp=mx1320x546&ctp=s1320x546&_nc_cat=105&ccb=1-7&_nc_sid=b96d88&_nc_ohc=TkXHSfYsBRsQ7kNvwHXQZKD&_nc_oc=AdpG8sZy5KtvI6vNqjvW_cyVGqukhKznuUlXroBt1L0LEU9rHUmt557StF4r8Gm7WgSxeTWVqbB7wNBXv-VkZtJn&_nc_zt=23&_nc_ht=scontent-lhr6-2.xx&_nc_gid=WFKkb5C9auRp7uHic7eVHw&_nc_ss=7f289&oh=00_Af5cQhpUYNc5FyVzDuxjw9qD-rUOrn_25MAKpJM6yFz-pw&oe=6A0D76C2"
  },
  {
    "id": 10,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1B8rie1BAd/",
    "canonicalUrl": "https://www.facebook.com/61577506953803/posts/%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AC%D8%A8%D9%84-%D8%B4%D8%A7%D9%85%D8%AE-%D9%84%D8%A7-%D8%AA%D9%87%D8%B2%D9%87-%D8%B1%D9%8A%D8%A7%D8%AD-%D8%A7%D9%84%D8%AD%D8%A7%D9%82%D8%AF%D9%8A%D9%86-%D8%B5%D9%88%D8%AA%D9%87-%D8%A7%D9%84%D8%B0%D9%8A-%D8%B2%D9%84%D8%B2%D9%84-%D8%B9%D8%B1%D9%88%D8%B4-%D8%A7%D9%84/122110727498916898/",
    "title": "الكاتبة عبير فتحي السقاف",
    "description": "الأستاذ جميل محمود عزالدين \nجبل شامخ لا تهزه رياح الحاقدين. صوته الذي زلزل عروش الكهنوت هو الذي أوجعكم، فذهبتتم تبحثون عن شائعات وتهم معلبة لتغطية فشلكم. سيبقى رمزاً إعلامياً وطنياً رغماً عن أنوف...",
    "image": "https://scontent-lhr8-1.xx.fbcdn.net/v/t39.30808-6/688978503_122110727474916898_1247071949093521507_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=108&ccb=1-7&_nc_sid=b96d88&_nc_ohc=yd50qs8nkHcQ7kNvwFmD666&_nc_oc=AdrY6gagfjHDDsnsWrcRWmHiyeURzr_y5nrUlai1iQBOX0YQuEDZlzD1otwu8AzyOey0BImDXs7SChiMVQh1uSRZ&_nc_zt=23&_nc_ht=scontent-lhr8-1.xx&_nc_gid=g2UE3LRtsNDpRNeQdFKxug&_nc_ss=7f289&oh=00_Af7qOdLTUksxMtMaVSLYLr5GqcmCrezGQhYA8ULktgql9Q&oe=6A0D765A"
  },
  {
    "id": 11,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1AznrvByEn/",
    "canonicalUrl": "https://www.facebook.com/m.bdalmjyd.mnsr/posts/%D8%A8%D8%B1%D8%A3%D9%8A%D9%8A-%D9%8A%D8%B9%D8%AF-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%85%D9%86-%D8%A7%D9%84%D8%A3%D8%B5%D9%88%D8%A7%D8%AA-%D8%A7%D9%84%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D8%A7%D9%84%D9%86%D8%A7%D8%AF%D8%B1%D8%A9-%D8%A7%D9%84%D8%AA%D9%8A-%D8%A7%D8%B3%D8%AA%D8%B7%D8%A7%D8%B9%D8%AA-%D8%A3%D9%86-%D8%AA%D8%AA%D8%AD%D8%B1%D8%B1-/2964366860434503/",
    "title": "م.عبدالمجيد منصر",
    "description": "برأيي، يعد جميل محمود عزالدين من الأصوات الإعلامية النادرة التي استطاعت أن تتحرر من قيود الحزبية والانتماءات الضيقة، ولم يكن يوماً أسيراً للمناطقية أو الطائفية، بل ارتقى بخطابه ليجعل الوطن قضيته...",
    "image": "https://scontent-lhr6-2.xx.fbcdn.net/v/t39.30808-6/689014988_2964366830434506_3862785458311420961_n.jpg?stp=dst-jpg_tt6&cstp=mx528x355&ctp=s528x355&_nc_cat=100&ccb=1-7&_nc_sid=b96d88&_nc_ohc=FGr-7SrTm9YQ7kNvwEKdtL0&_nc_oc=AdrdawxR-IMkFPo7h2uV7qo1FbFpApToJZlDU5Jj6KjMEvFUdbMXqxzjNoTYsrf07uZQv81R8T96SV9Byk_c0yVo&_nc_zt=23&_nc_ht=scontent-lhr6-2.xx&_nc_gid=yqBjjF8tnmlcdxgTHj9rew&_nc_ss=7f289&oh=00_Af4pCn44Vrgqel9ARMvrb8P6mXXV6ArtSgtrmoxfXljMGA&oe=6A0D650E"
  },
  {
    "id": 12,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18oWy6feyX/",
    "canonicalUrl": "https://www.facebook.com/waemalsofitaiz/posts/%D9%81%D9%8A-%D8%B2%D9%85%D9%86-%D8%A7%D9%84%D9%85%D8%AA%D8%BA%D9%8A%D8%B1%D8%A7%D8%AA-%D8%A7%D9%84%D9%83%D8%A8%D8%B1%D9%89-%D9%88%D8%A7%D9%84%D9%85%D9%86%D8%B9%D8%B7%D9%81%D8%A7%D8%AA-%D8%A7%D9%84%D8%AA%D8%A7%D8%B1%D9%8A%D8%AE%D9%8A%D8%A9-%D8%A7%D9%84%D9%82%D8%A7%D8%B3%D9%8A%D8%A9-%D8%AA%D8%A8%D8%B1%D8%B2-%D9%82%D8%A7%D9%85%D8%A7%D8%AA-%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D9%84%D8%A7-%D8%AA%D9%83%D8%AA%D9%81%D9%8A/3483625328451328/",
    "title": "وئام الصوفي",
    "description": "في زمن المتغيرات الكبرى والمنعطفات التاريخية القاسية، تبرز قامات إعلامية لا تكتفي بنقل الخبر، بل تصبح هي بذاتها جزءاً من معركة الوجود والهوية. ومن بين هذه الأسماء الشامخة، يتصدر الإعلامي القدير جميل...",
    "image": "https://scontent-lhr8-1.xx.fbcdn.net/v/t39.30808-6/687039169_3483625298451331_3064583629710072530_n.jpg?stp=dst-jpg_tt6&cstp=mx1338x1050&ctp=p600x600&_nc_cat=107&ccb=1-7&_nc_sid=b96d88&_nc_ohc=jWEPebmRzZEQ7kNvwEWHzxY&_nc_oc=AdrBWDCK9UCQEGb4va-bCPSDQYhi4e_pV995jyaVTDjkIz0vfLQ7NcXWLl9nzEqXoJa21k02338Pyj2d5kLnqL5G&_nc_zt=23&_nc_ht=scontent-lhr8-1.xx&_nc_gid=_308TZl2bdUE3SIkNW1RPQ&_nc_ss=7f289&oh=00_Af4UqCY8KhCbH15GAy53l5IlCYftH7X54Ua8yIUCBI6AcA&oe=6A0D46A2"
  },
  {
    "id": 13,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/18otrMgbMH/",
    "canonicalUrl": "https://www.facebook.com/abw.shhab.al.wady.891500/posts/%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%A7%D9%84%D9%81%D8%A7%D8%B6%D9%84-%D8%A7%D9%84%D8%A7%D8%B9%D9%84%D8%A7%D9%85%D9%8A-%D8%A7%D9%84%D9%82%D8%AF%D9%8A%D8%B1-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AD%D9%81%D8%B8%D9%87-%D8%A7%D9%84%D9%84%D9%87-%D9%88%D8%B1%D8%B9%D8%A7%D9%87-%D8%B8%D9%87%D8%B1%D8%AA-%D9%87%D8%B0%D9%87-%D8%A7%D9%84%D8%A7%D9%8A%D8%A7/4417171195232132/",
    "title": "ابو شهاب العواضي",
    "description": "الأستاذ الفاضل الاعلامي القدير \nجميل محمود عزالدين حفظه الله ورعاه  ظهرت هذه الايام. الحاسدين. والمسلطين اقلام الحسد ضده وانه فاسد وانه اخوه معه بيت وسياره وفلوس. شعب تعود على الحسد والمرض والقيل لن...",
    "image": "https://scontent-lhr8-2.xx.fbcdn.net/v/t39.30808-6/690763961_4417168421899076_805848398149374876_n.jpg?stp=dst-jpg_tt6&cstp=mx720x664&ctp=p600x600&_nc_cat=106&ccb=1-7&_nc_sid=b96d88&_nc_ohc=CNzMQ1SU0XwQ7kNvwFoUqz4&_nc_oc=AdpH8QCp1NhCmYh0O83ImTAPJirGdUiGd9Fsnx2RSLJ7AUrkRPaR6yI62aEIbTT4zkD2ztoDVBx1THH4pw_bmKMB&_nc_zt=23&_nc_ht=scontent-lhr8-2.xx&_nc_gid=PvtvDBC_AVxdB4TO9M6kAQ&_nc_ss=7f289&oh=00_Af7svviukOeemFvoFyiGGFW7jHIIW7Zwaj1iWSXeqZGXgw&oe=6A0D711E"
  },
  {
    "id": 14,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1GCpMEkCvA/",
    "canonicalUrl": "https://www.facebook.com/alsabahiyemen/posts/%D8%AC%D9%85%D9%8A%D9%84-%D8%B9%D8%B2-%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%A3%D9%8A%D9%82%D9%88%D9%86%D8%A9-%D8%A7%D9%84%D8%B4%D8%AC%D8%A7%D8%B9%D8%A9-%D9%88%D8%B6%D9%85%D9%8A%D8%B1-%D8%A7%D9%84%D9%88%D8%B7%D9%86%D9%86%D8%A4%D9%83%D8%AF-%D8%AA%D8%B6%D8%A7%D9%85%D9%86%D9%86%D8%A7-%D8%A7%D9%84%D9%85%D8%B7%D9%84%D9%82-%D9%88%D9%88%D9%82%D9%88%D9%81%D9%86%D8%A7-%D8%A7%D9%84%D8%AB%D8%A7%D8%A8%D8%AA-%D9%85%D8%B9-%D9%85%D9%86/27320301394253882/",
    "title": "أحمد الصباحي",
    "description": "جميل عز الدين أيقونة الشجاعة وضمير الوطن.\nنؤكد تضامننا المطلق ووقوفنا الثابت مع من جعل الشرف الوطني بوصلته الوحيدة.",
    "image": "https://scontent-lhr8-2.xx.fbcdn.net/v/t39.30808-6/689861758_27320225874261434_2890219879435376644_n.jpg?stp=dst-jpg_tt6&cstp=mx640x1302&ctp=p600x600&_nc_cat=101&ccb=1-7&_nc_sid=b96d88&_nc_ohc=wwDQHpb5RPAQ7kNvwEHehts&_nc_oc=AdqsyRy0Ua5psr6U8AbeOYAFoXzsdZHX5-1gNcSzxs2Nrtk6wF8TVgnXgwMd6Y2n8C6RtcUtVaOofac_hbUQYFsN&_nc_zt=23&_nc_ht=scontent-lhr8-2.xx&_nc_gid=9FVSiJ7M9Z7ZqqbrzCXU7Q&_nc_ss=7f289&oh=00_Af6HPw6V1w3_GEDAaruuK9kGiYJhBqZjExpl7w_aUb5-ew&oe=6A0D50E7"
  },
  {
    "id": 15,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1JPEVA6emw/",
    "canonicalUrl": "https://www.facebook.com/mhmd.rshad.alwhyby/posts/%D9%84%D9%85-%D9%8A%D8%B9%D8%B1%D9%81%D9%88%D8%A7-%D9%83%D9%8A%D9%81-%D9%8A%D8%B9%D9%8A%D8%A8%D9%88%D9%87-%D9%81%D9%82%D8%A7%D9%84%D9%88%D8%A7%D8%B9%D8%AC%D8%B2%D9%88%D8%A7-%D8%B9%D9%86-%D9%85%D9%8F%D8%A8%D8%A7%D8%B1%D8%B2%D8%AA%D9%87-%D9%81%D9%8A-%D9%85%D9%8A%D8%AF%D8%A7%D9%86-%D8%A7%D9%84%D8%AD%D9%8F%D8%AC%D8%A9-%D9%81%D8%A7%D8%B1%D8%AA%D8%AF%D9%91%D9%88%D8%A7-%D8%AE%D8%A7%D8%A6%D8%A8%D9%8A%D9%86-%D8%A5%D9%84%D9%89/1624244595929033/",
    "title": "محمد رشاد الوهيبي",
    "description": "\"لم يعرفوا كيف يعيبوه، فقالوا..!\n«عجزوا عن مُبارزته في ميدان الحُجة، فارتدّوا خائبين إلى أزقة الهمز واللمز؛ فالعاجزُ حين تُقهر حُجته، ويجفّ مَعين منطقِه، لا يجدُ مَلاذاً سوى الانحدار إلى سفاسف القول....",
    "image": "https://scontent-lhr8-1.xx.fbcdn.net/v/t39.30808-6/688940023_1624244572595702_1971355406454530222_n.jpg?stp=dst-jpg_tt6&cstp=mx945x1251&ctp=p600x600&_nc_cat=108&ccb=1-7&_nc_sid=b96d88&_nc_ohc=Ugp4Sz0tzRoQ7kNvwGu7MZe&_nc_oc=AdoF9oAc7G8hH41oZ-kGKgLmwuwE5xMz4iZa_qR5feLHau2w3AYfpu5zJR-AWNHrYp6Y3jJuDuMtYwlUqohMVqiA&_nc_zt=23&_nc_ht=scontent-lhr8-1.xx&_nc_gid=8LJ6r7ngucA9p_vLHTvkog&_nc_ss=7f289&oh=00_Af5BTxg0KxrnAzxbbjm3Bx7VlCvyPcnC2joHPRsmSjhKAw&oe=6A0D48B7"
  },
  {
    "id": 16,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1Aq6wa2qiw/",
    "canonicalUrl": "https://www.facebook.com/moh.alhamiidi/posts/%D8%A7%D9%84%D8%A3%D8%B3%D8%AA%D8%A7%D8%B0-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D9%87%D8%A7%D9%85%D8%A9-%D9%88%D9%82%D8%A7%D9%85%D8%A9-%D8%A5%D8%B9%D9%84%D8%A7%D9%85%D9%8A%D8%A9-%D9%88%D8%B7%D9%86%D9%8A%D8%A9-%D9%88%D9%85%D9%86-%D8%A3%D8%A8%D8%B1%D8%B2-%D9%88%D8%AC%D9%88%D9%87-%D8%A7%D9%84%D8%B4%D8%A7%D8%B4%D8%A9-%D8%A7%D9%84%D9%8A%D9%85%D9%86%D9%8A%D8%A9/2417871905355346/",
    "title": "محمد عبدالرحمن الحميدي",
    "description": "الأستاذ جميل محمود عزالدين هامة وقامة إعلامية وطنية، ومن أبرز وجوه الشاشة #اليمنية خلال سنوات عدة، كان إلى جانب الدولة والجمهورية منذ الوهلة الأولى، يعمل في ظل إمكانيات شحيحة، وميزانيات تكاد تكون...",
    "image": "https://scontent-lhr8-1.xx.fbcdn.net/v/t39.30808-6/686934024_2417871878688682_822272827617153299_n.jpg?stp=dst-jpg_tt6&cstp=mx1628x1440&ctp=p600x600&_nc_cat=107&ccb=1-7&_nc_sid=b96d88&_nc_ohc=Y71R-gXgf54Q7kNvwGd-1fX&_nc_oc=Adr-MOyCQfB6ca-2T7JWD5i0qDJI5KQVyRhudIJ5AujwvFWHlAf9ioC-_TKwT3x1zAxXhU-Qf_XXA54Peq4RdbKO&_nc_zt=23&_nc_ht=scontent-lhr8-1.xx&_nc_gid=elzTMwWGJf-Colyp0uKzfQ&_nc_ss=7f289&oh=00_Af45O7Hu5kTHcWJ7AQ6m2KYg5MPOCG1YljymSVtpDsfwdw&oe=6A0D622E"
  },
  {
    "id": 17,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1bsvE2VGg8/",
    "canonicalUrl": "https://www.facebook.com/Mohammed774542424/posts/%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%B9%D8%B1%D9%81%D9%86%D8%A7-%D9%88%D8%B7%D9%86%D9%8A%D8%AA%D9%87-%D9%88%D8%AD%D8%A8%D9%87-%D9%84%D8%A8%D9%84%D8%A7%D8%AF%D9%87-%D9%88%D8%B3%D9%85%D8%B9%D9%86%D8%A7-%D8%B5%D9%88%D8%AA%D9%87-%D9%88%D9%83%D9%84%D9%85%D8%AA-%D8%A7%D9%84%D8%AD%D9%82-%D9%85%D9%86-%D9%84%D8%B3%D8%A7%D9%86%D9%87-%D9%81%D9%8A-%D9%88/122250771776308621/",
    "title": "محمد عبدالملك اليوسفي",
    "description": "جميل محمود عزالدين عرفنا وطنيته وحبه لبلاده وسمعنا صوته وكلمت الحق من لسانه في وجه الحوسي ووجه مليسيات الإمارات \nلم نسمع منه الا كل خير سلاحه وواجهته نحو الحوسي ولم يقدح بي عر.. ض احد \nهذا ماعرفت عنه...",
    "image": "https://scontent-lhr6-2.xx.fbcdn.net/v/t39.30808-6/690611930_122250771752308621_730865611444082946_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=100&ccb=1-7&_nc_sid=b96d88&_nc_ohc=JNeUM7ed5UgQ7kNvwGjCPc0&_nc_oc=AdrodITEgSQ5WDx6xZQr_Xnpyf904aVG6mhrbooLDHTlRVgixJH8fgRkeMbtFpCVPT28vUrfbj9uL5qgVlMwp2Xa&_nc_zt=23&_nc_ht=scontent-lhr6-2.xx&_nc_gid=wJsg2Jy1fCFki5x-_tzpuw&_nc_ss=7f289&oh=00_Af7NdO9kzcNCZ1UDTUWXwxMk6WV_4hHwNsByKw3E6ycd2g&oe=6A0D4A77"
  },
  {
    "id": 18,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1bXYNWcHtL/",
    "canonicalUrl": "https://www.facebook.com/share/1bXYNWcHtL/",
    "title": "",
    "description": "",
    "image": ""
  },
  {
    "id": 19,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18gsWAAsXV/",
    "canonicalUrl": "https://www.facebook.com/share/18gsWAAsXV/",
    "title": "",
    "description": "",
    "image": ""
  },
  {
    "id": 20,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1LCuheyr6s/",
    "canonicalUrl": "https://www.facebook.com/alqyl.fysl.alsh.wry.alsh.wry/posts/%D9%86%D9%82%D8%B7%D8%A9_%D9%86%D8%B8%D8%A7%D9%85_%D9%88%D8%AA%D8%B5%D8%AD%D9%8A%D8%AD_%D9%85%D9%81%D8%A7%D9%87%D9%8A%D9%85-%D9%88%D9%83%D9%84%D9%85%D8%A9-%D8%AD%D9%82-%D9%8A%D8%AC%D8%A8-%D8%A3%D9%86-%D8%AA%D9%8F%D9%82%D8%A7%D9%84-%D9%84%D8%A3%D9%86-%D8%A7%D9%84%D8%B5%D9%85%D8%AA-%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D9%84%D9%8A%D8%B3-%D8%AE%D8%B0%D9%84%D8%A7%D9%86%D9%8B%D8%A7-%D9%81%D9%82%D8%B7-%D9%88%D8%A5/122272180004216402/",
    "title": "فيصل الشعوري الشعوري",
    "description": "*#نقطة_نظام_وتصحيح_مفاهيم*  \nوكلمة حق يجب أن تُقال، لأن الصمت اليوم ليس خذلانًا فقط، وإنما خيانة مكتملة الأركان.  \nــــــــــــــــــــــــــــــــــــــــــــ\nلا أعرف #مجلي_الصمدي، ولكني أعرف جميل...",
    "image": "https://scontent-lhr8-1.xx.fbcdn.net/v/t39.30808-6/690870786_122272179968216402_2156452392953497465_n.jpg?stp=dst-jpg_tt6&cstp=mx640x640&ctp=s600x600&_nc_cat=111&ccb=1-7&_nc_sid=b96d88&_nc_ohc=O2fQMHyCH20Q7kNvwFDSkxe&_nc_oc=AdrAbsHKS2COTKZig0egW9QEBhSptsWypopmRjH4ZfLjFEzaBW9UCXnmpd1wn88Ph7PfQgIz3ffFkvIevPLwJJOY&_nc_zt=23&_nc_ht=scontent-lhr8-1.xx&_nc_gid=E6IuADeo-ozh0H9WCQ31CQ&_nc_ss=7f289&oh=00_Af4868cf6JUjwkaxUnyUnOSJDbA85PrnPYlGMArXEscnew&oe=6A0D5115"
  },
  {
    "id": 21,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/18U831WbQ4/",
    "canonicalUrl": "https://www.facebook.com/100009338670352/posts/%D8%A7%D9%84%D8%A7%D8%AE%D8%AA%D9%84%D8%A7%D9%81-%D9%85%D8%B9-%D8%AC%D9%85%D9%8A%D9%84-%D9%85%D8%AD%D9%85%D9%88%D8%AF-%D8%B9%D8%B2%D8%A7%D9%84%D8%AF%D9%8A%D9%86-%D8%AD%D9%82-%D9%85%D9%83%D9%81%D9%88%D9%84-%D9%84%D9%83%D9%86-%D8%AA%D8%AD%D9%88%D9%8A%D9%84-%D8%A7%D9%84%D9%86%D9%82%D8%AF-%D8%A5%D9%84%D9%89-%D8%A5%D8%B3%D8%A7%D8%A1%D8%A9-%D8%B4%D8%AE%D8%B5%D9%8A%D8%A9-%D9%88%D8%A7%D8%AA%D9%87%D8%A7%D9%85%D8%A7%D8%AA/4455806328073946/",
    "title": "ابو يحي سليمان",
    "description": "الاختلاف مع جميل محمود عزالدين  حق مكفول، لكن تحويل النقد إلى إساءة شخصية واتهامات بالتسلق والتنطع لا يخدم أحد، خصوصًا عندما نتحدث عن شخص له تاريخ إعلامي وحضور معروف.\n\nجميل قد تتفق أو تختلف معه، لكن...",
    "image": "https://scontent-lhr8-2.xx.fbcdn.net/v/t39.30808-6/691607310_982575281091338_2406927203322018541_n.jpg?stp=dst-jpg_tt6&cstp=mx521x1156&ctp=s521x1156&_nc_cat=103&ccb=1-7&_nc_sid=cae128&_nc_ohc=rnCaXEmyzhsQ7kNvwFJioJ4&_nc_oc=Adrl2BHeZJUvLo2ULu96sc7iBLrxZ97gGwGrU4SMyyCY-1mp4HEL0Pt6u8jALmw9tmre29YOG2KJ3tVxQiNfTZDs&_nc_zt=23&_nc_ht=scontent-lhr8-2.xx&_nc_gid=cybPjbOFocqO-80PXVICgw&_nc_ss=7f289&oh=00_Af7LCWqqQ1bf3M_vHgcD1Zds9egw49NQTJh9-zJD9qmAoA&oe=6A0D670C"
  },
  {
    "id": 22,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1GQRwLRn3L/",
    "canonicalUrl": "https://www.facebook.com/kmal.mhmd.alb.dany/posts/%D9%87%D8%A8%D8%B7%D8%AA-%D8%A8%D8%B9%D9%88%D8%B6%D8%A9-%D8%B9%D9%84%D9%89-%D9%86%D8%AE%D9%84%D8%A9-%D9%81%D9%84%D9%85%D8%A7-%D8%A7%D8%B1%D8%A7%D8%AF%D8%AA-%D8%A7%D9%86-%D8%AA%D8%B7%D9%8A%D8%B1-%D9%82%D8%A7%D9%84%D8%AA-%D9%84%D9%84%D9%86%D8%AE%D9%84%D8%A9-%D8%AA%D9%85%D8%A7%D8%B3%D9%83%D9%8A-%D8%A3%D9%8A%D8%AA%D9%87%D8%A7-%D8%A7%D9%84%D9%86%D8%AE%D9%84%D8%A9-%D9%81%D8%A3%D9%86%D8%A7-%D8%B3%D9%88%D9%81-/2794017204301657/",
    "title": "كمال محمد البعداني",
    "description": "هبطت بعوضة على نخلة ، فلما ارادت ان تطير قالت للنخلة ؛ تماسكي أيتها النخلة ، فأنا سوف اطير ! فضحكت النخلة وقالت للبعوضة : والله ما شعرت بك يوم وقعت  فكيف أشعر بك اذا طرت ؟ فلا تلفت لطنين البعوض يا...",
    "image": "https://scontent-lhr6-1.xx.fbcdn.net/v/t39.30808-6/696005598_2793994164303961_3473060185864530094_n.jpg?stp=cp6_dst-jpg_tt6&cstp=mx996x662&ctp=p600x600&_nc_cat=110&ccb=1-7&_nc_sid=b96d88&_nc_ohc=gKBn8kTjXzIQ7kNvwHk9IDw&_nc_oc=Adq1A5An5pBU_MsXjtHvYfX7xp5S2cNwhllWYdZPGATHZ5q1Up0CDRYsDtlNspGrgrP6-MjpedRlWoaP2vTtGxlc&_nc_zt=23&_nc_ht=scontent-lhr6-1.xx&_nc_gid=_vWCnLMA0ysXkAbd8sczzQ&_nc_ss=7f289&oh=00_Af5_NQSgxB1FLoDnsV3LnOH1iK7V7Tf6Twdue8hEtTMXqw&oe=6A0D4D06"
  },
  {
    "id": 23,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/1D2My2SzNj/",
    "canonicalUrl": "https://www.facebook.com/alqyl.fysl.alsh.wry.alsh.wry/posts/%D9%8A%D9%85%D9%86%D9%8A-%D8%A7%D9%84%D8%A3%D8%B5%D9%84-%D9%87%D8%B0%D8%A7-%D9%86%D8%B3%D8%A8%D9%8A%D9%82%D8%AF-%D8%AD%D8%A8%D8%A7%D9%86%D8%A7-%D8%A7%D9%84%D9%84%D9%87-%D8%A3%D8%B9%D9%84%D9%89-%D8%A7%D9%84%D8%B1%D8%AA%D8%A8%D9%90%D8%A3%D9%8A-%D8%A3%D8%AE-%D8%B9%D9%84%D9%85%D8%A7%D9%8B-%D9%88%D9%85%D8%A7-%D9%8A%D8%AF%D8%B1%D9%8A%D9%83-%D9%85%D9%86-%D9%8A%D8%B1%D8%AA%D9%82%D9%8A-%D8%A7%D9%84%D8%B9%D8%B1%D8%B4/122272361660216402/",
    "title": "فيصل الشعوري الشعوري",
    "description": "­يمني الأصل هذا نسبي\nقد حبانا الله أعلى الرتبِ\n\nأي أخ علماً وما يدريك من\n يرتقي العرش وهام السحبِ\n\nهكذا جئنا وفي أقدارنا \nأن نكون الرأس دون الذنبِ\n\nيمنيٌ جئت من أرض سبأ\nأحمل الحق بأسمى الكتبِ\n\nلا تسل...",
    "image": ""
  },
  {
    "id": 24,
    "type": "facebook",
    "sourceUrl": "https://www.facebook.com/share/p/1apimmLbgC/",
    "canonicalUrl": "https://www.facebook.com/ALSlahi.Abdullh.YEM/posts/%D8%A7%D9%84%D8%AA%D9%84%D9%81%D8%B2%D9%8A%D9%88%D9%86-%D8%A7%D9%84%D8%B1%D8%B3%D9%85%D9%8A-%D8%AD%D9%8A%D9%86-%D9%8A%D8%B5%D8%A8%D8%AD-%D8%A7%D9%84%D8%B5%D9%88%D8%AA-%D9%87%D8%AF%D9%81%D8%A7%D8%AF%D8%B9%D9%88%D9%86%D8%A7-%D9%86%D9%82%D8%B1%D8%A3-%D8%A8%D9%85%D9%88%D8%B6%D9%88%D8%B9%D9%8A%D8%A9-%D8%A7%D9%84%D8%AD%D9%85%D9%84%D8%A9-%D8%A7%D9%84%D9%85%D9%85%D9%86%D9%87%D8%AC%D8%A9-%D8%B6%D8%AF-%D8%A7%D9%84%D8%A3%D8%B3%D8%AA/2865211433822125/",
    "title": "عبدالله الصلاحي",
    "description": "التلفزيون الرسمي… حين يصبح الصوت هدفا\n\nدعونا نقرأ بموضوعية الحملة الممنهجة ضد الأستاذ جميل عز الدين\nاولا نتفق على ان التلفزيون الرسمي هو العنوان الأوضح لصوت الدولة والمرآة التي تعكس موقفها وخياراتها...",
    "image": ""
  }
];
